// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialLoginAndRegistrationWeb.Models;

#nullable disable

namespace TrialLoginAndRegistrationWeb.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrialLoginAndRegistrationWeb.Models.Clothes", b =>
                {
                    b.Property<int>("Clothes_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Clothes_ID"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Clothes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Clothes_ID");

                    b.HasIndex("Clothes");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("TrialLoginAndRegistrationWeb.Models.Order", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"), 1L, 1);

                    b.Property<string>("Comm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Order_Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Phone_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rent_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Order_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TrialLoginAndRegistrationWeb.Models.Clothes", b =>
                {
                    b.HasOne("TrialLoginAndRegistrationWeb.Models.Order", null)
                        .WithMany("Clothes_ID")
                        .HasForeignKey("Clothes");
                });

            modelBuilder.Entity("TrialLoginAndRegistrationWeb.Models.Order", b =>
                {
                    b.Navigation("Clothes_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
